CREATE TABLE USER (
	USER_ID INT,
	FIRST_NAME VARCHAR(50),
	LAST_NAME VARCHAR(50),
	ADDRESS VARCHAR(100),
	FK_CITY_ID INT,
	FESS BOOLEAN
);

CREATE TABLE CITY (
	CITY_ID INT,
	CITY_NAME VARCHAR(50)
);

INSERT INTO USER VALUES (1, 'PINCO', 'PALLINO', 'VIA DEI PAZZI', 1, TRUE);
INSERT INTO USER VALUES (2, 'JOHN', 'DOE', NULL, 4, TRUE);
INSERT INTO USER VALUES (3, 'PAOLINO', 'PAPERINO', 'VIA DEI PAPERI', 2, FALSE);
INSERT INTO USER VALUES (4, 'FRED', 'FLINSTONE', 'VIA ROSSI', 3, FALSE);

INSERT INTO CITY VALUES (1, 'MILANO');
INSERT INTO CITY VALUES (2, 'ROMA');
INSERT INTO CITY VALUES (3, 'NAPOLI');
INSERT INTO CITY VALUES (4, 'NEW YORK');
